# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkkFN7eV1wmcklh1OK7JSoRtfUvRW0Mz
"""

import pandas as pd
df = pd.DataFrame ({
               'Ism Familiya' :    ['ABDUXAKIMOV XURSANDBEK ORIBJON O‘G‘LI',' AHMADALIYEV ABBOSXON SAIDJON O‘G‘LI',' AZIZIBLOYEV HOJIAKBAR ABDUJALIL O‘G‘L',' DO‘LTABOYEV MUHAMMADJON G‘ANIJON O‘G‘LI',' MADAMINJONOV BAXTIYORJON SHERZOD O‘G‘LI',' MAMATVALIYEV DILSHODBEK XALIMJON O‘G‘LI',' MIRZAHAMIDOV JALOLIDDIN MUZAFFAR O‘G‘LI',' NE’MATOVA DILDORAXON XAYRULLOJON QIZI',' NURMUHAMMADOV MUHAMMAD MUXIDDIN O‘G‘LI',' QAMBARALIYEVA NIGORAXON MUXAMMADJON QIZI','QAMBAROV SAMANDARBEK XAYDARALI O‘G‘LI',' RAXMONOV BEKZODJON MUXAMMADMUROT O‘G‘LI',' SHAMSIDINOV SHERZODJON HOJIBOY ZODA','SOBIROV MUHAMMADJON IBROHIM O‘G‘L','SODIQOVA MAXLIYOXON SAFARALI QIZI','SULAYMONOVA MAXLIYOXON VALIJON QIZI','TURG‘UNBOYEV DIYORBEK OYBEK O‘G‘LI','  YO‘LDASHEV XUSNIDDIN XASANBOY O‘G‘LI',' YUSUBJONOV YAXYOBEK O‘TKIRJON O‘G‘LI' ] ,

               'yoshi':   ['20', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30', '30'],
               'kursi':   ['3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3'] ,
                  'tugulgan yili':['2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005',]
                 })
print(df)

df.to_excel('guruh.xlsx', index=False, sheet_name='sheet1')